name: VuePress Deploy
# 工作流的名称，如果省略，则使用当前文件名

# 从工作流生成的工作流运行的名称，如果省略，则使用提交时的commit信息
run-name: Deploy by ${{ github.actor }}

# 触发部署的条件
on:
  # 每当 push 到 master 分支时触发部署
  push:
    branches: [master]


jobs:
    
  # 任务的名称，不设置则默认my_first_job
  docs:
    
    name: build-and-deploy
    
    # 运行所需要的虚拟机环境
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # 选择要使用的 pnpm 版本
          version: 8
          # 使用 pnpm 安装依赖
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 20
          # 缓存 pnpm 依赖
          cache: pnpm

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm docs:build

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        id: deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: src/.vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN_WANZAIDABAO0724 }}


      - name: Get deployment time
        if: always()
        run: |
          end_time=$(date +%s)
          start_time=${{ steps.deploy.outputs.start_time }}
          if [ -z "$start_time" ]; then
            echo "DEPLOY_TIME=Deployment failed" >> $GITHUB_ENV
          else
            duration=$((end_time - start_time))
            echo "DEPLOY_TIME=Deployment took $duration seconds" >> $GITHUB_ENV
          fi

      - name: Send Telegram message
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            VuePress部署状态: ${{ job.status }}
            ${{ env.DEPLOY_TIME }}
